# Generated by Django 4.1.3 on 2023-02-02 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0018_alter_book_book_price_alter_book_overtime_fine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(max_length=600, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=600, unique=True, verbose_name='name'),
        ),
    ]
