# Generated by Django 4.1.3 on 2023-02-02 07:21

from django.db import migrations, models
import system.models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0020_alter_book_name_alter_genre_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.IntegerField(choices=[(1, 'Male'), (2, 'Female')], default=1),
        ),
        migrations.AddField(
            model_name='student',
            name='section',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='year',
            field=models.IntegerField(choices=[(1, '1st Year'), (2, '2nd Year'), (3, '3rd Year'), (4, '4th Year')], default=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=11, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='student',
            name='school_id',
            field=models.CharField(default=system.models.generate_school_id, max_length=10, unique=True, verbose_name='ID Number'),
        ),
    ]
