# Generated by Django 4.1.3 on 2023-02-02 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0021_student_address_student_gender_student_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='qualified',
            field=models.IntegerField(choices=[(1, 'Qualified'), (0, 'Not Qualified')], default=1),
        ),
    ]
