# Generated by Django 4.1.3 on 2023-02-02 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0024_book_inventory_stock_alter_book_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='summary',
        ),
    ]
