# Generated by Django 4.1.3 on 2023-02-02 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0028_alter_incomingtransaction_book_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outgoingtransaction',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
