# Generated by Django 4.1.3 on 2023-02-02 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0029_outgoingtransaction_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='penalty',
            name='book_borrowed',
        ),
        migrations.RemoveField(
            model_name='penalty',
            name='borrower',
        ),
        migrations.AddField(
            model_name='penalty',
            name='transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='system.outgoingtransaction'),
        ),
    ]
