# Generated by Django 4.1.3 on 2023-02-03 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0030_remove_penalty_book_borrowed_remove_penalty_borrower_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='penalty',
            name='date_paid',
            field=models.DateField(null=True),
        ),
    ]
