# Generated by Django 4.1.3 on 2023-02-03 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0031_penalty_date_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='book',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='book',
            name='last_modified',
        ),
        migrations.RemoveField(
            model_name='book',
            name='name',
        ),
        migrations.RemoveField(
            model_name='book',
            name='was_deleted',
        ),
    ]
