# Generated by Django 4.1.3 on 2023-02-03 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0032_remove_book_created_date_remove_book_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outgoingtransaction',
            name='returned',
            field=models.BooleanField(default=False),
        ),
    ]
